### ISSUE TITLE
A question with lightfall(waterfall)

### ISSUE THREAD

**Issue by kingniu4** [WiIIiam278/PAPIProxyBridge#111]
When the server is loaded first and then lightfall is enabled, the plugin works normally.
But when I first opened lightfall and then started the server, PAPI did not load successfully.
This will cause the PAPI to display errors after the server restarts normally.

It seems that PAPIProxyBridge can't detect the server restart automatically

Plugins:HuskChat/Multiverse-Core/PAPI/PAPIProxyBridge/Luckperms
![image](https://github.com/WiIIiam278/PAPIProxyBridge/assets/98977392/9f2cc4e9-7c41-463b-a553-38c08dc7ff8d)

**Comment by WiIIiam278** [comment]
hey,
odd--but I suggest it's probably more likely a HuskChat issue in this case?
