### ISSUE TITLE
Placeholder sync/forwarding

### ISSUE THREAD

**Issue by Nikkilectric** [WiIIiam278/PAPIProxyBridge#120]
Would it be possible to add functionality to get placeholders from another backend server? 

Example: 

%survival_(plugin)_level% to get the players level from a specific server's plugin (survival), then forwarding that to the proxy?

**Comment by WiIIiam278** [comment]
I think that's probably out of scope for the goals of the plugin at this time.

**Comment by WiIIiam278** [comment]
Actually, this also just isn't technically possible. Players have to be online on the server to receive & process the plugin messages. Plus most Placeholder expansions require the user to be online.

**Comment by Nikkilectric** [comment]
> Actually, this also just isn't technically possible. Players have to be online on the server to receive & process the plugin messages. Plus most Placeholder expansions require the user to be online.

Ah- alright- I just saw it was possible with the discontinued https://spigotmc.org/resources/deleted.56288/ resource so I figured I'd try to make the request here. Sorry for the trouble!
