### ISSUE TITLE
`findServers()` returns the wrong type

### ISSUE THREAD

**Issue by Andre601** [WiIIiam278/PAPIProxyBridge#125]
Through a bug report did I find out, that `findServers()` now returns a set instead of a List.
Why was this breaking(!) change made? And why was there no mention in the updates?

**Comment by Andre601** [comment]
This is especially bad give that it was a patch version update, while this is in fact a breaking change, going against proper semantic versioning (Assuming your API follows that).

**Comment by WiIIiam278** [comment]
Hi there, @alexdev03 made this change and it looks like I didn't notice during the review.

That's on me for not noticing that a breaking change was made. It should be rolled back and I consider this a bug; i'll revert that functionality.

**Comment by Andre601** [comment]
Understandable.

I [implemented a fix on my end](https://codeberg.org/Andre601/AdvancedServerList/commit/833f8f5dbb134931fb7d7461a4c477355e351992) that should make it work with both the old and new return type.

**Comment by WiIIiam278** [comment]
@Andre601 We've pushed an update out now to resolve this. Apologies for the, thanks for your work maintaining PAPI :)
