### ISSUE TITLE
Retries are broken

### ISSUE THREAD

**Issue by Apehum** [WiIIiam278/PAPIProxyBridge#131]
If the backend server doesn't have the PAPIProxyBridge plugin installed, [formatPlaceholders](https://github.com/WiIIiam278/PAPIProxyBridge/blob/81b7ee964a385fd96d8dacf566fc0d595c7cbfa6/common/src/main/java/net/william278/papiproxybridge/api/PlaceholderAPI.java#L128) will get stuck forever due to a deadlock caused by retries

You can reproduce this deadlock using the following example (using Kotlin):
```kotlin
import java.util.concurrent.CompletableFuture
import java.util.concurrent.TimeUnit

fun main() {
    test(3).get()
}

fun test(times: Int): CompletableFuture<Void> =
    CompletableFuture<Void>()
        .orTimeout(50L, TimeUnit.MILLISECONDS)
        .exceptionally {
            println("Test $times")
            test(times - 1).get()
        }
```

The easiest fix is to use `exceptionallyAsync` instead of `exceptionally`, but maybe you have better ideas on how to fix it

**Comment by WiIIiam278** [comment]
Fixed in #141
