### ISSUE TITLE
Bad Timings Report

### ISSUE THREAD

**Issue by Ste3et** [WiIIiam278/PAPIProxyBridge#137]
Dear William278 sorry that i need to contact you,

For the first thank your for your PAPIProxyBridge it make so mutch easer for us to switch to Velocity.
But i need you to inform that your BukkitEntityScheduler increase our TPS lose, i do an oldschool Timings report but since your PAPIProxyBridge is used the Server runs somethimes in wierd workload situations.
Did i have the option on my PaperServer to enhance the Performance a bit by reducing the TickSpeed of the Runnable or can you give me some other instructions to do?

Here is my super duper Timings Report https://timings.aikar.co/dev/?id=4ad1b912ea44456e80ab1dc4c741ef18

**Comment by WiIIiam278** [comment]
Fixed in #141
