### ISSUE TITLE
[question] Best aproach to support Placeholder parsing within an event on Proxy

### ISSUE THREAD

**Issue by Andre601** [WiIIiam278/PAPIProxyBridge#20]
I was asked a few days ago to implement support for PAPIProxyBridge on the Bungee and Velocity side of my plugin.

The thing is, that my plugin relies on Events from the Proxy to do things, including the parsing of Placeholders (It's own ones supplied through its own API).
This, as of right now, is handled synchronous, so adding PAPIProxyBridge support would most likely throw a wrench in this entire thing as it would now need to deal with CompletableFuture's and their resulting asynchronous nature.

So, I'm now asking what could be the best aproach here to support this plugin while handling the events in a proper way (As in making sure my plugin is "done" before any subsequent plugin listening to the same event would deal with it) to avoid weird mix ups or alike...
I was told in the past that using `get()` is a bad idea here, as it kinda destroys the purpose of CompletableFutures in general, so I would love to avoid that and other bad aproaches...

The events are handled in a platform-independant, core class:
https://github.com/Andre601/AdvancedServerList/blob/master/core/src/main/java/ch/andre601/advancedserverlist/core/events/PingEventHandler.java

The respective Ping events for BungeeCord and Velocity respectively:
https://github.com/Andre601/AdvancedServerList/blob/master/bungeecord/src/main/java/ch/andre601/advancedserverlist/bungeecord/events/PingEvent.java
https://github.com/Andre601/AdvancedServerList/blob/master/velocity/src/main/java/ch/andre601/advancedserverlist/velocity/events/PingEvent.java

**Comment by Andre601** [comment]
I think it could be a good aproach to use the cache idea and simply return `%placeholder%`s as-is while there is no return value yet from the CompletedFuture...

Tho, I'm not entirely sure how this could look like in practice and I also would have the problem to figure out and notice when a value changed...
On Bungee and Velocity this wouldn't be an issue since values are cached on your end for 30 seconds according to the info provided on the Spigot page, but I'm considering to use this plugin as a general tool (As in parse placeholders through it if present instead of PAPI) to not have a separate handling. Tho, that could then be problematic on the Bukkit-side as there, values could obviously be returned faster.

Maybe a mix of both could be an idea: On Proxy-side use the cache aproach with a hold time of 30 seconds after retrieval and on Bukkit use default PAPI as I would only set placeholders in either case...

**Comment by WiIIiam278** [comment]
That sounds fairly reasonable.
As for the caching thing -- It's been on my mind to provide API for optionally setting a cache time when making a request (including turning it off); would that help?
I certainly agree it'd be easier in terms of maintenance to just depend on the one plugin rather than have to fallback to base depending on PAPI on Bukkit if you can't help it.

**Comment by Andre601** [comment]
I noticed that CF offers a `getNow(String valueIfAbsent)` which could be what I want here, which is returning the CF value if completed, or return a different value, if absent...

Tho, Idk if it is safe to just call `formatPlaceholders` x times and the plugin returns only one CF every 30 seconds, or if I should still keep a cache holding the CF generated here...

**Comment by Andre601** [comment]
Okay.
I just wasn't sure if calling the formatPlaceholders method several times would cause your plugin to prepare multiple CF or if it would actually prepare one and return it for any subsequent call with the same key.

**Comment by Andre601** [comment]
This would be my current aproach:
```java
    @Override
    public String parsePAPIPlaceholders(String text, BungeePlayerImpl player){
        // TODO: Find a way to check if PAPIProxyBridge is active.
        
        try{
            CompletableFuture<String> future = PingEventHandler.getPAPI().formatPlaceholders(text, player.getUUID());
            return future.getNow(text);
        }catch(IllegalArgumentException ex){
            return text;
        }
    }
```

**Comment by WiIIiam278** [comment]
Yeah so each call would create a new future for each call to my format method; just that it would return an already completed future through the static #completedFuture method if the passed text currently had a cached result. A new future that completes later is only made if the formatted text isn't in the cache. I think that should be fine perf-wise and your implementation looks good

**Comment by Andre601** [comment]
After testing, I realized something... If I'm not mistaken does this plugin require the player to be present on the backend servers to work, right? Not only because of the limitations of plugin messaging, but also because from what I saw you use a class called OnlinePlayer, which makes me guess it's a required player on the server?

Would there be any workaround (like caching placeholder results indefinitely after player left) to this?
Because my plugin actually modifies the display of the server in a player's multiplayer window, meaning the Player in question wouldn't be on any server while the content is shown to them...

**Comment by WiIIiam278** [comment]
Yeah so, indeed, plugin messaging requires an online player -- you'll want to implement caching on your end if you'd like to workaround this more than likely or you'll get IllegalArgumentExceptions (though technically the internal caching won't throw this)

**Comment by Andre601** [comment]
The only problem is that, as I mentioned, my plugin doesn't work with online players, therefore the placeholders wouldn't resolve (Unless offline player is used in these cases by the expansions) while the player isn't on the server... Unless I misunderstand the setup.

Like I understand it as the player you want the placeholders to be resolved for needs to be on the server.
Or do you mean *any* online connection is valid as long as there is a connection between the server with PAPI and the Proxy?

**Comment by WiIIiam278** [comment]
Any online connection that's been online for more then a few ticks is fine for sending / receiving plugin messages; right now there's just no way in this api of specifying to format placeholders for anyone other than the message sender. I should probably make this more resilient where it'll find someone to send the message if it can't resolve the passed uuid.

**Comment by Andre601** [comment]
Would be apreciated as right now my plugin would have no way to actually obtain the parsed string for the player since they aren't on the server.

I feel like a system like this could be the best aproach:

- Use the Player's connection if they are online. Allows to parse all placeholders no matter if they use Player or OfflinePlayer
- In case Player isn't online, use a random online player connection for communication and use OfflinePlayer instead of Player. Limits Placeholders supported a bit, but allows Plugins to have placeholders parse for players not online.

Like have a fallback that relies on OfflinePlayer (for Bukkit Servers) when the Player in question is not online but a connection for plugin msg is present.

**Comment by WiIIiam278** [comment]
@Andre601 I've added a new way of passing a `formatFor` UUID which will be resolved as an OfflineUser on the backend if it differs from the `requester` player -- in this way, you can now do as you requested :)

I've also added a way of setting the cache timings through the API.

Have a good one!

**Comment by Andre601** [comment]
Looking at the diff between 1.2 and 1.1, I can see that you're still using the Player instance on the Bukkit side...
Unless I misunderstand stuff is this still not gonna work as a Player is bound to an online player... You can (and should) use the OfflinePlayer here to format placeholders for, as it otherwise still won't work...

Obviously I can be wrong here and I'll try to make some tests where possible, but from a first look do I not see a possible fix for the issue I'm facing. Will get back to you with further info once I did some basic tests.

**Comment by Andre601** [comment]
I also noticed another flaw that doesn't solve the issue at all, if I understand it correctly...

When I get the new method correctly would I now provide two UUIDs, one for the requester and one for who the placeholders should be parsed.

The issue I see when checking the code is the fact that you're using the requester's UUID for the connection?
Like you take the UUID for the requester and try to find a player for it to then do a connection with to then handle placeholders for the other UUID?
If my understanding is correct does that mean that the method STILL requires a online player UUID to be provided, meaning that my plugin at the very least would need to try and obtain a UUID from a connected player on the proxy.

Again: My plugin by nature does **not** work with players being online, but with players that are offline, since they aren't on the server yet. Having to now find a random online player to sacrifice the UUID for feels really stupid to do... That's if I understand this entire thing right...

**Comment by WiIIiam278** [comment]
> If my understanding is correct does that mean that the method STILL requires a online player UUID to be provided, meaning that my plugin at the very least would need to try and obtain a UUID from a connected player on the proxy.

Correct -- and this sentence here is the unfortunate crux of the issue, as sending a plugin message always requires an online player connection to forward the message. What I've done here is separate the "requester" (person forwarding the plugin message) and "toFormat" (person being formatted). Both are represented as UUIDs, of course. Indeed, you'd still need at least one online player to do this, so you'd need to pick any random online player to pass to the "requester" argument.

What I suppose I could do, is do that for you -- whereby I randomly select a player. I'm really not sure this is great behavior to include in an API like this, though.

----
The plugin messaging channel: 

This is a weird, very _"Spigot":tm:_ API -- whereby when they designed BungeeCord, in lieu of fleshing out a proper BungeeCord <--> SpigotMC communication channel and building an API around that, they simply repurposed the Minecraft plugin messaging channel packet Mojang added to help Bukkit/Mod devs out back in 2011 to "forward" data through connected player packets. It's weird, it's annoying, doesn't work if the player hasn't completed the login handshake which can take an indeterminate number of ticks, and the result is essentially everyone gives up and just is told to "use RabbitMQ or Redis". I want to keep this lightweight, config-free, and really _don't_ want to have to do that as this is meant to be a small, standalone thing.

**Comment by Andre601** [comment]
Yeah. The main issue I can see is, that with a setup where not every server has PAPI and this bridge on, there is a coin toss on who will be selected. If everything goes great, the right server is selected and stuff is handled as it should, but if it goes bad, the wrong server is selected and stuff isn't handled...

Maybe an API method could be added that would make the bridge call all servers and collect all the ones that return a success message (Like send a dummy request that the bridges respond to), which the API user could then use to determine what players to use for a possible request. Alternatively do the same, but return lists of UUIDs from these servers, to directly know what players there are that would return a valid response...

Tho, to be completely honest would I say that you should throw away the plugin message aproach and go with a websocket connection at this point, since the current system - while easy - is just too limited to be really beneficial.
Tho, I also consider my case to be a huge edge-case at best.

I can understand if you don't want to go this way. Especially since I can't think of an automated aproach that wouldn't require a configuration to define IPs and ports for those to work.

**Comment by WiIIiam278** [comment]
Thanks for your input. Yeah, I think as you can see the balance between complexity and use cases is the problem here :( 

A websocket is something I've looked at in the past, but issues with port forwarding needs and security always put me off doing that, not to mention of course the added complexity and need to maintain it. 

I could look into some sort of tracking system I suppose. I think in terms of my own personal interest in doing either that or moving to some other message broking system, it's pretty much zero atm. I'm absolutely open to a good PR of course. It's a shame to leave it imperfect like this, but I do hope at least this suits a good majority of the use cases where people want to use placeholders on their proxy.

Side note but, has your team considered a rewrite of PAPI abstracting out the common bits of API and doing some networking stuff to support backend/frontend/other server platforms and such? That'd probably have more flexibility to do this sort of thing

**Comment by Andre601** [comment]
The only thing that comes close to this is the curren v3 rewrite of PlaceholderAPI that should bring support for multiple platforms like BungeeCord, Velocity and Sponge.
But the date of its first release is farther away than world peace (I'm joking but the *best* estimate for a first build or any progress/continuation is around 2024).

Also, not my team. I'm just the annoying people of a country who want changes from the government, only to get a delayed, shitty implementation of it. /j

**Comment by Andre601** [comment]
Was just thinking, but perhaps it would be an idea to either make a separate plugin for a more permanent `server <-> server` communication (websocket, redis, etc.), or support an existing solution like https://github.com/Phoenix616/ConnectorPlugin/

Obviously, this can and should be optional to use, but it would be quite a nice solution while keeping your plugin configuration free and simple.
If plugin present: hook into it; if not: Use default plugin msg stuff.

I myself was thinking about making a plugin for websocket communication, but why re-invent the wheel when other stuff would exist?

**Comment by WiIIiam278** [comment]
Yeah, I like that approach. Not sure if ConnectorPlugin's the perfect choice but it seems solid enough?

**Comment by Andre601** [comment]
Idk either. Never used it and honestly won't as setting up some redis stuff or whatever on my PC for simple testing feels like overkill.
