### ISSUE TITLE
update 1.20.4 plz

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [WiIIiam278/PAPIProxyBridge#93]
i got some issue when i update to 1.20.4
https://paste.ubuntu.com/p/gPW5TxvxHf/

**Comment by WiIIiam278** [comment]
Looks like PlaceholderAPI isn't installed on your server :)

**Comment by xiaoyueyoqwq** [comment]
> Looks like PlaceholderAPI isn't installed on your server :)

uhm...my server is already install a PlaceholderAPI but this PlacehloderAPI's version is Folia's version(DEL-NULL)
and PAPIBridge's version is the special version too, i add folia-support in plugin.yml to let it running on my server
![image](https://github.com/WiIIiam278/PAPIProxyBridge/assets/71379165/4511b8d4-968b-4eca-a1f6-5877adcde5b2)

**Comment by xiaoyueyoqwq** [comment]
![image](https://github.com/WiIIiam278/PAPIProxyBridge/assets/71379165/9e432dc6-3bfc-42d7-b2f0-5805c9bb84ed)

**Comment by WiIIiam278** [comment]
Sounds like you filed an issue that you created by yourself by modifying it? :) I don't support Folia just yet; the Bukkit/Velocity plugin here should work just fine on 1.20.4 though.

**Comment by xiaoyueyoqwq** [comment]
> Sounds like you filed an issue that you created by yourself by modifying it? :) I don't support Folia just yet; the Bukkit/Velocity plugin here should work just fine on 1.20.4 though.

yes ur right lol*
hope that folia-support be done in 2023 ;)
